apiVersion: v1
kind: Service
metadata:
  name: be-test-grpc-service
spec:
  type: NodePort
  ports:
  - name: rest
    port: 80
    protocol: TCP
    targetPort: 80
  - name: grpc
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: be-test-grpc-service