apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: be-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-api
  template:
    metadata:
      labels:
        app: be-api
    spec:
      containers:
      - name: be-api
        image: lisyaoran51/be-api:latest
        ports:
        - containerPort: 80
          name: rest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /alive
            port: rest
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 30  
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: rest
          initialDelaySeconds: 10
          periodSeconds: 3
        envFrom: 
        - configMapRef: 
            name: be-api-config