apiVersion: v1
kind: ConfigMap
metadata: 
  name: be-wallet-config
data:
  SERVER_LISTEN_ADDRESS: '0.0.0.0'
  SERVER_LISTEN_PORT: '80'
  GRPC_SERVER_LISTEN_ADDRESS: '0.0.0.0'
  GRPC_SERVER_LISTEN_PORT: '9999'
  SERVICE_NAME_AS_ROOT: 'false'

  DATABASE_DIALECT: 'mysql'
  DATABASE_USERNAME: 'root'
  DATABASE_PASSWORD: 'root'
  DATABASE_HOST: 'mysql-service'
  DATABASE_PORT: '3306'
  DATABASE_NAME: 'be-wallet'

  REDIS_ENDPOINT: 'redis-service:6379'
  REDIS_DB: '0'
  REDIS_POOLSIZE: '100'
  REDIS_IDLE_TIMEOUT: '60000'
  REDIS_MAX_IDLE_CONNECTIONS: '10'
  REDIS_CONNECTION_IDLE_TIMEOUT_MS: '60000'
  REDIS_PASSWORD: '123456'

  SERVICE_NAME: 'be-wallet'
  SERVER_ENV: 'dev'
  PRODUCTION_ENVIRONMENT: 'false'
  LOG_LEVEL: '4'
  STACKDRIVER_ENABLED: 'true'
  GRPC_CONNECT_TIMEOUT_MS: '60000'
  PROJECT_ID: 'be-wallet'

  MEMBER_GRPC_HOST: 'be-member-service'
  MEMBER_GRPC_PORT: '9999'
