apiVersion: apps/v1 # for kubectl versions >= 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: be-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be-test-service
  template:
    metadata:
      labels:
        app: be-test-service
    spec:
      containers:
      - name: be-test-service
        image: lisyaoran51/be-test-service:latest
        ports:
        - containerPort: 80
          name: rest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /alive
            port: rest
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 30  
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: rest
          initialDelaySeconds: 10
          periodSeconds: 3