apiVersion: v1
kind: Service
metadata:
  name: be-test-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30390
    protocol: TCP
    targetPort: 80
  selector:
    app: be-test-service